### ISSUE TITLE
matrices for INDEX (Low CPU usage) how to solve

### ISSUE THREAD

**Issue by xiaoyaojianghuzai** [AlexandrovLab/SigProfilerMatrixGenerator#179] opened 2024-04-20 05:01 UTC
Dear Professor @mdbarnesUCSD 
Did it take more time for generating matrices for INDEX than for DBS and MBS?
I find it doesn't finish after much more time than that or DBS and MBS?

**Comment by xiaoyaojianghuzai** [comment] 2024-04-22 13:54
i use cpu=-1(the default setting) but it turns out that the computer has low cpu usage both linux and windows. Did the package use mutipleprocess to increase the speed?

**Comment by mdbarnesUCSD** [comment] 2024-04-22 16:23
Hi @xiaoyaojianghuzai,

SigProfilerMatrixGenerator is not using multiprocessing and does not have a cpu parameter. Are you referring to SigProfilerExtractor?

**Comment by xiaoyaojianghuzai** [comment] 2024-04-23 05:07
yes，I find  SigProfilerExtractor  use this function. But the little cpu usage confuses me

**Comment by mdbarnesUCSD** [comment] 2024-04-23 20:37
I am closing this issue here as the issue is specific to SigProfilerExtractor:
https://github.com/AlexandrovLab/SigProfilerExtractor/issues/243

**Closed by mdbarnesUCSD** 2024-04-23 20:37 UTC
